### ISSUE TITLE
can't update on banana-pi [ERR! This is most likely a problem with the usb package]

### ISSUE THREAD

**Issue by jensebub** [philip1986/pimatic-led-light#17]
since last update, i got some errors during the installation:

```
16:13:50.387 [pimatic] info: Installing: "pimatic-led-light" from npm-registry.
16:13:53.863 [pimatic, npm] info: http GET https://registry.npmjs.org/pimatic-led-light
16:13:55.164 [pimatic, npm] info: http GET https://registry.npmjs.org/lodash
16:13:55.209 [pimatic, npm] info: http GET https://registry.npmjs.org/blinkstick/1.1.1
16:13:55.244 [pimatic, npm] info: http GET https://registry.npmjs.org/cassert
16:13:55.267 [pimatic, npm] info: http GET https://registry.npmjs.org/color
16:13:55.288 [pimatic, npm] info: http GET https://registry.npmjs.org/node-milight-promise
16:13:55.308 [pimatic, npm] info: http GET https://registry.npmjs.org/node-milight-rf24
16:13:57.003 [pimatic, npm] info: http GET https://registry.npmjs.org/callsite
16:13:57.206 [pimatic, npm] info: http GET https://registry.npmjs.org/color-convert
16:13:57.236 [pimatic, npm] info: http GET https://registry.npmjs.org/color-string
16:13:57.504 [pimatic, npm] info: http GET https://registry.npmjs.org/bluebird
16:13:57.684 [pimatic, npm] info: http GET https://registry.npmjs.org/serialport
16:13:59.085 [pimatic, npm] info: http GET https://registry.npmjs.org/color-name
16:13:59.642 [pimatic, npm] info: http GET https://registry.npmjs.org/usb/1.0.4
16:14:08.436 [pimatic, npm] info: http GET https://registry.npmjs.org/usb-shyp-darwin-x64/1.0.4
16:14:08.472 [pimatic, npm] info: http GET https://registry.npmjs.org/usb-shyp-win32-x64/1.0.4
16:14:08.508 [pimatic, npm] info: http GET https://registry.npmjs.org/usb-shyp-win32-ia32/1.0.4
16:14:08.521 [pimatic, npm] info: http GET https://registry.npmjs.org/bindings-shyp
16:14:08.558 [pimatic, npm] info: http GET https://registry.npmjs.org/nan
16:14:09.867 [pimatic, npm] info: WARN optional dep failed, continuing usb-shyp-win32-x64@1.0.4
16:14:09.885 [pimatic, npm] info: WARN optional dep failed, continuing usb-shyp-darwin-x64@1.0.4
16:14:09.890 [pimatic, npm] info: WARN optional dep failed, continuing usb-shyp-win32-ia32@1.0.4
16:14:10.520 [pimatic, npm] info: > usb@1.0.4 install /root/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb
16:14:10.525 [pimatic, npm] info: > node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild
16:14:15.431 [pimatic, npm] info: make: Entering directory `/root/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb/build'
16:14:15.450 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
16:14:18.817 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
16:14:21.412 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
16:14:22.149 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
16:14:24.481 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
16:14:24.935 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
16:14:25.555 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
16:14:25.885 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
16:14:25.937 [pimatic, npm] info: ../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
16:14:25.952 [pimatic, npm] info: <command-line>:0:0: note: this is the location of the previous definition
16:14:26.149 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
16:14:30.487 [pimatic, npm] info:   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
16:14:30.693 [pimatic, npm] info: ../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: Datei oder Verzeichnis nicht gefunden
16:14:30.700 [pimatic, npm] info: compilation terminated.
16:14:31.199 [pimatic, npm] info: make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Fehler 1
16:14:31.210 [pimatic, npm] info: make: Leaving directory `/root/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb/build'
16:14:31.236 [pimatic, npm] info: gyp ERR! build error
16:14:31.261 [pimatic, npm] info: gyp ERR! stack Error: `make` failed with exit code: 2
16:14:31.267 [pimatic, npm] info: gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
16:14:31.271 [pimatic, npm] info: gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
16:14:31.275 [pimatic, npm] info: gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
16:14:31.279 [pimatic, npm] info: gyp ERR! System Linux 3.4.104-bananian
16:14:31.283 [pimatic, npm] info: gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
16:14:31.308 [pimatic, npm] info: gyp ERR! cwd /root/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb
16:14:31.312 [pimatic, npm] info: gyp ERR! node -v v0.10.24
16:14:31.317 [pimatic, npm] info: gyp ERR! node-gyp -v v0.12.1
16:14:31.321 [pimatic, npm] info: gyp ERR! not ok
16:14:31.326 [pimatic, npm] info: http GET https://registry.npmjs.org/optimist
16:14:31.331 [pimatic, npm] info: http GET https://registry.npmjs.org/sf/0.1.7
16:14:31.336 [pimatic, npm] info: http GET https://registry.npmjs.org/async/0.9.0
16:14:31.340 [pimatic, npm] info: http GET https://registry.npmjs.org/bindings/1.2.1
16:14:31.346 [pimatic, npm] info: http GET https://registry.npmjs.org/debug
16:14:31.354 [pimatic, npm] info: http GET https://registry.npmjs.org/nan
16:14:31.420 [pimatic, npm] info: http GET https://registry.npmjs.org/ms/0.7.1
16:14:31.430 [pimatic, npm] info: http GET https://registry.npmjs.org/wordwrap
16:14:31.438 [pimatic, npm] info: http GET https://registry.npmjs.org/minimist
16:14:31.589 [pimatic, npm] info: > serialport@1.7.4 install /root/pimatic-app/node_modules/pimatic-led-light/node_modules/node-milight-rf24/node_modules/serialport
16:14:31.605 [pimatic, npm] info: > node-pre-gyp install --fallback-to-build
16:14:32.545 [pimatic, npm] info: module.js:340
16:14:32.562 [pimatic, npm] info:     throw err;
16:14:32.573 [pimatic, npm] info:           ^
16:14:32.627 [pimatic, npm] info: Error: Cannot find module './pre-binding'
16:14:32.633 [pimatic, npm] info:     at Function.Module._resolveFilename (module.js:338:15)
16:14:32.637 [pimatic, npm] info:     at Function.Module._load (module.js:280:25)
16:14:32.643 [pimatic, npm] info:     at Module.require (module.js:364:17)
16:14:32.652 [pimatic, npm] info:     at require (module.js:380:17)
16:14:32.656 [pimatic, npm] info:     at Object.<anonymous> (/root/pimatic-app/node_modules/pimatic-led-light/node_modules/node-milight-rf24/node_modules/serialport/node_modules/node-pre-gyp/lib/node-pre-gyp.js:38:16)
16:14:32.660 [pimatic, npm] info:     at Module._compile (module.js:456:26)
16:14:32.664 [pimatic, npm] info:     at Object.Module._extensions..js (module.js:474:10)
16:14:32.668 [pimatic, npm] info:     at Module.load (module.js:356:32)
16:14:32.671 [pimatic, npm] info:     at Function.Module._load (module.js:312:12)
16:14:32.675 [pimatic, npm] info:     at Module.require (module.js:364:17)
16:14:33.450 [pimatic, npm] info: ERR! usb@1.0.4 install: `node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild`
16:14:33.464 [pimatic, npm] info: ERR! Exit status 1
16:14:33.468 [pimatic, npm] info: ERR!
16:14:33.475 [pimatic, npm] info: ERR! Failed at the usb@1.0.4 install script.
16:14:33.479 [pimatic, npm] info: ERR! This is most likely a problem with the usb package,
16:14:33.484 [pimatic, npm] info: ERR! not with npm itself.
16:14:33.490 [pimatic, npm] info: ERR! Tell the author that this fails on your system:
16:14:33.496 [pimatic, npm] info: ERR!     node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild
16:14:33.501 [pimatic, npm] info: ERR! You can get their info via:
16:14:33.505 [pimatic, npm] info: ERR!     npm owner ls usb
16:14:33.508 [pimatic, npm] info: ERR! There is likely additional logging output above.
16:14:33.512 [pimatic, npm] info: ERR! System Linux 3.4.104-bananian
16:14:33.516 [pimatic, npm] info: ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-led-light"
16:14:33.520 [pimatic, npm] info: ERR! cwd /root/pimatic-app
16:14:33.568 [pimatic, npm] info: ERR! node -v v0.10.24
16:14:33.572 [pimatic, npm] info: ERR! npm -v 1.3.21
16:14:33.576 [pimatic, npm] info: ERR! code ELIFECYCLE
16:14:33.752 [pimatic, npm] info: ERR!
16:14:33.766 [pimatic, npm] info: ERR! Additional logging details can be found in:
16:14:33.774 [pimatic, npm] info: ERR!     /root/pimatic-app/npm-debug.log
16:14:33.779 [pimatic, npm] info: ERR! not ok code 0
16:14:33.848 [pimatic] error: Error running "npm install pimatic-led-light"
```

regards 
jensebub

**Comment by philip1986** [comment]
Yes, it looks like an issue with usb and serialport. Have try to run `npm install usb`? Which OS you are running? If it is Debian you can also try this `sudo apt-get install libudev-dev`, since the root of the issue seams to be that libudev.h is missing.

**Comment by jensebub** [comment]
apt-get install libudev-dev solved the issue. 

Thx a lot
jensebub

**Comment by philip1986** [comment]
Nice :)

**Comment by Nears** [comment]
Hi, I have the same problem, but libudev-dev is allready installed ... :-( 
Any other suggestions how to solve this?
