### ISSUE TITLE
Installations fails on raspberry pi 2

### ISSUE THREAD

**Issue by mwittig** [philip1986/pimatic-led-light#18]
```
npm http GET https://registry.npmjs.org/pimatic-led-light/latest

npm http 200 https://registry.npmjs.org/pimatic-led-light/latest

npm http GET https://registry.npmjs.org/pimatic-led-light

npm http 200 https://registry.npmjs.org/pimatic-led-light

npm http GET https://registry.npmjs.org/pimatic-led-light/-/pimatic-led-light-0.1.0.tgz

npm http 200 https://registry.npmjs.org/pimatic-led-light/-/pimatic-led-light-0.1.0.tgz

npm http GET https://registry.npmjs.org/pimatic-led-light/0.1.0

npm http 200 https://registry.npmjs.org/pimatic-led-light/0.1.0

npm http GET https://registry.npmjs.org/pimatic-led-light/-/pimatic-led-light-0.1.0.tgz

npm http 200 https://registry.npmjs.org/pimatic-led-light/-/pimatic-led-light-0.1.0.tgz

npm http GET https://registry.npmjs.org/node-milight-promise

npm http GET https://registry.npmjs.org/blinkstick/1.1.1

npm http GET https://registry.npmjs.org/node-milight-rf24

npm http GET https://registry.npmjs.org/lodash

npm http GET https://registry.npmjs.org/cassert

npm http GET https://registry.npmjs.org/color

npm http GET https://registry.npmjs.org/iwy_master/0.2.2

npm http 200 https://registry.npmjs.org/lodash

npm http 200 https://registry.npmjs.org/node-milight-promise

npm http GET https://registry.npmjs.org/node-milight-promise/-/node-milight-promise-0.0.2.tgz

npm http GET https://registry.npmjs.org/lodash/-/lodash-3.9.3.tgz

npm http 200 https://registry.npmjs.org/blinkstick/1.1.1

npm http GET https://registry.npmjs.org/blinkstick/-/blinkstick-1.1.1.tgz

npm http 200 https://registry.npmjs.org/iwy_master/0.2.2

npm http GET https://registry.npmjs.org/iwy_master/-/iwy_master-0.2.2.tgz

npm http 200 https://registry.npmjs.org/cassert

npm http 200 https://registry.npmjs.org/color

npm http 200 https://registry.npmjs.org/node-milight-promise/-/node-milight-promise-0.0.2.tgz

npm http 200 https://registry.npmjs.org/lodash/-/lodash-3.9.3.tgz

npm http 200 https://registry.npmjs.org/node-milight-rf24

npm http 200 https://registry.npmjs.org/blinkstick/-/blinkstick-1.1.1.tgz

npm http GET https://registry.npmjs.org/cassert/-/cassert-0.1.2.tgz

npm http 200 https://registry.npmjs.org/iwy_master/-/iwy_master-0.2.2.tgz

npm http GET https://registry.npmjs.org/color/-/color-0.8.0.tgz

npm http GET https://registry.npmjs.org/node-milight-rf24/-/node-milight-rf24-0.0.3.tgz

npm http 200 https://registry.npmjs.org/cassert/-/cassert-0.1.2.tgz

npm http 200 https://registry.npmjs.org/color/-/color-0.8.0.tgz

npm http 200 https://registry.npmjs.org/node-milight-rf24/-/node-milight-rf24-0.0.3.tgz

npm http GET https://registry.npmjs.org/callsite

npm http GET https://registry.npmjs.org/color-string

npm http GET https://registry.npmjs.org/color-convert

npm http GET https://registry.npmjs.org/bluebird

npm http 200 https://registry.npmjs.org/callsite

npm http GET https://registry.npmjs.org/serialport

npm http GET https://registry.npmjs.org/callsite/-/callsite-1.0.0.tgz

npm http GET https://registry.npmjs.org/color

npm http 200 https://registry.npmjs.org/callsite/-/callsite-1.0.0.tgz

npm http 200 https://registry.npmjs.org/color-string

npm http 200 https://registry.npmjs.org/bluebird

npm http GET https://registry.npmjs.org/color-string/-/color-string-0.3.0.tgz

npm http 200 https://registry.npmjs.org/serialport

npm http 200 https://registry.npmjs.org/color-convert

npm http GET https://registry.npmjs.org/color/-/color-0.7.3.tgz

npm http GET https://registry.npmjs.org/bluebird/-/bluebird-2.9.30.tgz

npm http 200 https://registry.npmjs.org/color-string/-/color-string-0.3.0.tgz

npm http GET https://registry.npmjs.org/serialport/-/serialport-1.7.4.tgz

npm http GET https://registry.npmjs.org/color-convert/-/color-convert-0.5.3.tgz

npm http 200 https://registry.npmjs.org/color/-/color-0.7.3.tgz

npm http 200 https://registry.npmjs.org/serialport/-/serialport-1.7.4.tgz

npm http 200 https://registry.npmjs.org/bluebird/-/bluebird-2.9.30.tgz

npm http 200 https://registry.npmjs.org/color-convert/-/color-convert-0.5.3.tgz

npm http GET https://registry.npmjs.org/usb/1.0.4

npm http GET https://registry.npmjs.org/color-name

npm http 200 https://registry.npmjs.org/usb/1.0.4

npm http GET https://registry.npmjs.org/usb/-/usb-1.0.4.tgz

npm http 200 https://registry.npmjs.org/usb/-/usb-1.0.4.tgz

npm http 200 https://registry.npmjs.org/color-name

npm http GET https://registry.npmjs.org/color-name/-/color-name-1.0.0.tgz

npm http 200 https://registry.npmjs.org/color-name/-/color-name-1.0.0.tgz

npm http GET https://registry.npmjs.org/color-string/-/color-string-0.2.4.tgz

npm http 200 https://registry.npmjs.org/color-string/-/color-string-0.2.4.tgz

npm http GET https://registry.npmjs.org/usb-shyp-win32-x64/1.0.4

npm http GET https://registry.npmjs.org/usb-shyp-win32-ia32/1.0.4

npm http GET https://registry.npmjs.org/usb-shyp-darwin-x64/1.0.4

npm http GET https://registry.npmjs.org/bindings-shyp

npm http GET https://registry.npmjs.org/nan

npm http 200 https://registry.npmjs.org/bindings-shyp

npm http 200 https://registry.npmjs.org/usb-shyp-darwin-x64/1.0.4

npm http GET https://registry.npmjs.org/bindings-shyp/-/bindings-shyp-0.2.3.tgz

npm http GET https://registry.npmjs.org/usb-shyp-darwin-x64/-/usb-shyp-darwin-x64-1.0.4.tgz

npm http 200 https://registry.npmjs.org/usb-shyp-win32-x64/1.0.4

npm http 200 https://registry.npmjs.org/usb-shyp-win32-ia32/1.0.4

npm http 200 https://registry.npmjs.org/nan

npm http GET https://registry.npmjs.org/usb-shyp-win32-ia32/-/usb-shyp-win32-ia32-1.0.4.tgz

npm http GET https://registry.npmjs.org/usb-shyp-win32-x64/-/usb-shyp-win32-x64-1.0.4.tgz

npm http 200 https://registry.npmjs.org/usb-shyp-darwin-x64/-/usb-shyp-darwin-x64-1.0.4.tgz

npm http 200 https://registry.npmjs.org/bindings-shyp/-/bindings-shyp-0.2.3.tgz

npm http 200 https://registry.npmjs.org/usb-shyp-win32-x64/-/usb-shyp-win32-x64-1.0.4.tgz

npm http 200 https://registry.npmjs.org/usb-shyp-win32-ia32/-/usb-shyp-win32-ia32-1.0.4.tgz

npm WARN optional dep failed, continuing usb-shyp-darwin-x64@1.0.4

npm WARN optional dep failed, continuing usb-shyp-win32-ia32@1.0.4

npm WARN optional dep failed, continuing usb-shyp-win32-x64@1.0.4

> usb@1.0.4 install /home/pi/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb

> node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild

make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb/build'

CC(target) Release/obj.target/libusb/libusb/libusb/core.o

CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o

CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o

CC(target) Release/obj.target/libusb/libusb/libusb/io.o

CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o

CC(target) Release/obj.target/libusb/libusb/libusb/sync.o

CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o

CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o

../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]

<command-line>:0:0: note: this is the location of the previous definition

CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o

CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o

../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory

compilation terminated.

libusb.target.mk:119: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed

make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb/build'

make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1

gyp ERR! build error

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)

gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)

gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:789:12)

gyp ERR! System Linux 3.18.11-v7+

gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-led-light/node_modules/blinkstick/node_modules/usb

gyp ERR! node -v v0.10.24

gyp ERR! node-gyp -v v0.12.1

gyp ERR! not ok

npm http GET https://registry.npmjs.org/debug

npm http GET https://registry.npmjs.org/optimist

npm http GET https://registry.npmjs.org/sf/0.1.7

npm http GET https://registry.npmjs.org/async/0.9.0

npm http GET https://registry.npmjs.org/bindings/1.2.1

npm http GET https://registry.npmjs.org/nan

npm http 200 https://registry.npmjs.org/debug

npm http 200 https://registry.npmjs.org/optimist

npm http GET https://registry.npmjs.org/debug/-/debug-2.2.0.tgz

npm http GET https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz

npm http 200 https://registry.npmjs.org/async/0.9.0

npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz

npm http 200 https://registry.npmjs.org/sf/0.1.7

npm http GET https://registry.npmjs.org/sf/-/sf-0.1.7.tgz

npm http 200 https://registry.npmjs.org/debug/-/debug-2.2.0.tgz

npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz

npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz

npm http 200 https://registry.npmjs.org/bindings/1.2.1

npm http 200 https://registry.npmjs.org/sf/-/sf-0.1.7.tgz

npm http GET https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz

npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz

npm http GET https://registry.npmjs.org/ms/0.7.1

npm http 200 https://registry.npmjs.org/ms/0.7.1

npm http GET https://registry.npmjs.org/ms/-/ms-0.7.1.tgz

npm http GET https://registry.npmjs.org/minimist

npm http GET https://registry.npmjs.org/wordwrap

npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.1.tgz

npm http 200 https://registry.npmjs.org/minimist

npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz

npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz

npm http 200 https://registry.npmjs.org/wordwrap

npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz

npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz

> serialport@1.7.4 install /home/pi/pimatic-app/node_modules/pimatic-led-light/node_modules/node-milight-rf24/node_modules/serialport

> node-pre-gyp install --fallback-to-build

module.js:340

throw err;

^

Error: Cannot find module '/home/pi/pimatic-app/node_modules/pimatic-led-light/node_modules/node-milight-rf24/node_modules/serialport/node_modules/.bin/node-pre-gyp'

at Function.Module._resolveFilename (module.js:338:15)

at Function.Module._load (module.js:280:25)

at Function.Module.runMain (module.js:497:10)

at startup (node.js:119:16)

at node.js:902:3

npm ERR! usb@1.0.4 install: `node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the usb@1.0.4 install script.

npm ERR! This is most likely a problem with the usb package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR! node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild

npm ERR! You can get their info via:

npm ERR! npm owner ls usb

npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.11-v7+

npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "update" "pimatic-led-light"

npm ERR! cwd /home/pi/pimatic-app

npm ERR! node -v v0.10.24

npm ERR! npm -v 1.3.21

npm ERR! code ELIFECYCLE

npm ERR!

npm ERR! Additional logging details can be found in:

npm ERR! /home/pi/pimatic-app/npm-debug.log

npm ERR! not ok code 0
```

**Comment by jensebub** [comment]
`apt-get install libudev-dev` solved my Prob during install ;)

see also: https://github.com/philip1986/pimatic-led-light/issues/17

greetings
jensebub

**Comment by mwittig** [comment]
@jensebub Thanks. I'll give it a try and will report back.

**Comment by philip1986** [comment]
Didi it work? Can I close this issue?

**Comment by mwittig** [comment]
See my PR to document the dependency as part of the README

**Comment by philip1986** [comment]
fixed by https://github.com/philip1986/pimatic-led-light/pull/25
